
application: flask-jtable
version: 2
runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /[^.]*
  script: main.app

- url: /
  static_dir: static
  application_readable: true

libraries:
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?.*\.py[co]$
- ^\.git$